name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Test (fuzzy)
        run: cargo test --verbose -F fuzzy

  check-conditional:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: ["gcs", "htslib", "fuzzy"]
    steps:
      - uses: actions/checkout@v3
      - name: Check (default)
        run: cargo check
      - name: Check (all features)
        run: cargo check --all-features
      - name: Check (no features)
        run: cargo check --no-default-features
      - name: Check (each feature)
        run: cargo check --no-default-features -F ${{ matrix.feature }}

  fmt_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy --verbose
